// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonarTrack.Infrastructure.Data;

#nullable disable

namespace SonarTrack.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SonarTrackDbContext))]
    [Migration("20240817191239_QualityGateNull")]
    partial class QualityGateNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SonarTrack.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Bugs")
                        .HasColumnType("int");

                    b.Property<int>("CodeSmells")
                        .HasColumnType("int");

                    b.Property<int>("CognitiveComplexity")
                        .HasColumnType("int");

                    b.Property<decimal>("Coverage")
                        .HasColumnType("money");

                    b.Property<int>("CyclomaticComplexity")
                        .HasColumnType("int");

                    b.Property<decimal>("DuplicatedLinesDensity")
                        .HasColumnType("money");

                    b.Property<decimal>("EffortToFixTechnicalDebt")
                        .HasColumnType("money");

                    b.Property<string>("MaintainabilityRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("NonCommentingLinesOfCode")
                        .HasColumnType("int");

                    b.Property<int>("OpenIssues")
                        .HasColumnType("int");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("QualityGate")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReliabilityRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SecurityRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Vulnerabilities")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Analyses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
